---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: mavenwebappdeployment
spec:
 replicas: 2
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: vishwajeetkore/mavenwebapp
 template:
  metadata:
   name: mavenwebapppod
   labels:
     app: vishwajeetkore/mavenwebapp	 
  spec: 
    containers:
    - name: mavenwebappcontainer
      image: ashokit/maven-web-app:v3
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: mavenwebappsvc
spec:
  type: LoadBalancer
  selector:
   app: vishwajeetkore/mavenwebapp
  ports:
   - port: 80
     targetPort: 8080
...
