apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.labels.app }}-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: myapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
